### ISSUE TITLE
Question about normalize-resample.sh

### ISSUE THREAD

**Issue by yxixi** [mindslab-ai/voicefilter#10]
Thank you for your great job! I have a question when I tried to run the project.
I set 'N' as my CPU core number , then I input 'chmod a+x normalize-resample.sh'.
However, after I input './normalize-resample.sh ', there is no output on the command line. Is this normal?
Furthermore, what is the function of this script?
```
Next, copy utils/normalize-resample.sh to root directory of unzipped data folder. Then:

vim normalize-resample.sh # set "N" as your CPU core number.
chmod a+x normalize-resample.sh
./normalize-resample.sh # this may take long
```
Looking for your reply!

**Comment by seungwonpark** [comment]
Hi, @yxixi 
- Yes, there will be no output on the command line.
- It converts wav files with arbitrary sample rate into 16kHz, normalized wav files.

**Comment by yxixi** [comment]
Got it, thank you for your reply! @seungwonpark

**Comment by pranshurastogi29** [comment]
hey i am having an error while running the normalize-resample.sh the 
output is 
WARNING: Audio stream has a duration of less than 3 seconds. Normalization may not work. See https://github.com/slhck/ffmpeg-normalize/issues/87 for more info.
i am using libri 360 and i am working in colab

**Comment by seungwonpark** [comment]
According to my recent study, you may simply skip normalization. It won’t affect much.
