### ISSUE TITLE
Question when preprocessing wav files

### ISSUE THREAD

**Issue by yxixi** [mindslab-ai/voicefilter#11]
Hi all, I encountered a question when I tried to preprocess wav files.
When I input this
```
python generator.py -c [config yaml] -d [data directory] -o [output directory] -p [processes to run]
```
the command line display error messages like this:

```
Traceback (most recent call last):
  File "generator.py", line 98, in <module>
    os.makedirs(args.out_dir, exist_ok=False)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```
```

Traceback (most recent call last):
  File "generator.py", line 128, in <module>
    for spk in train_folders]
TypeError: glob() got an unexpected keyword argument 'recursive'
```

```
Traceback (most recent call last):
  File "generator.py", line 150, in <module>
    with Pool(cpu_num) as p:
AttributeError: __exit__

```
When I queried these questions, I found that they were all due to incompatibility of Python versions.My Python version is 2.7. Is "generator. py" only suitable for Python 3.5 environment? Is there any way to run this code in Python 2.7?

Looking forward to your reply!

**Comment by stegben** [comment]
Yes you should use python3. Also, the support of python 2 will be dropped next year. So it would be better that you transfer to python 3.6+
