### ISSUE TITLE
Question when training VoiceFilter

### ISSUE THREAD

**Issue by yxixi** [mindslab-ai/voicefilter#12]
Hi, it's me again:)
Because of insufficient computer storage,I skipped the following step:
```

Preprocess wav files

In order to boost training speed, perform STFT for each files before training by:

python generator.py -c [config yaml] -d [data directory] -o [output directory] -p [processes to run]

This will create 100,000(train) + 1000(test) data. (About 160G)

```

Then I downloaded embedder.pt, train-clear-100.tar.gz and dev-clean.tar.gz. I unziped tar.gz files and put those unzipped file folders to the  root directory of voicefilter.I also  specifying train_dir, test_dir at config.yaml, such as:

```
  train_dir: '/home/../voicefilter/train/train-clean-100'
  test_dir: '/home/../voicefilter/dev/dev-clean'
```

After that, when I enter this instruction:

`python trainer.py -c [config yaml] -e [path of embedder pt file] -m [name]`

Error prompts pop up on the screen:**AssertionError: no training file found**

I want to know which step I made a mistake, or what configuration was missing? Thanks! REALLY looking forward to your reply!

**Comment by seungwonpark** [comment]
Hi, @yxixi 

The given error should be caused by skipping of the preprocessing step.
You may try to fix code to perform STFT on the fly while training.
