### ISSUE TITLE
The files from the dataset are in flac format

### ISSUE THREAD

**Issue by bhaveshgg17** [mindslab-ai/voicefilter#2]
Changing the bash script for .flac didn't help either.

**Comment by seungwonpark** [comment]
Hi, @bhaveshgg17 
Can you please elaborate about this issue? What bash script are you talking about?

**Comment by bhaveshgg17** [comment]
Hello, @seungwonpark 
The .sh script provided in utils folder. I somehow managed to run the script (used ffmpeg instead of ffmpeg-normalize). 
Running the generator.py had some issues for me.
Can you please elaborate what changes to make in congif.yaml before running generator.py? Running it as is gives an error `"ValueError: Sample larger than population or is negative"` on ` spk1, spk2 = random.sample(train_spk, 2)`
Using` numpy.ravel `on _train_spk_ and them using` random.sample()` gives an error `FileNotFoundError: [Errno 2] No such file or directory: '/home/foobar/Desktop/voicefilter-master/p'`

**Comment by bhaveshgg17** [comment]
Hello, @seungwonpark 
The .sh script provided in utils folder. I somehow managed to run the script (used ffmpeg instead of ffmpeg-normalize). 
Everything works for now. Thanks for the code!

**Comment by seungwonpark** [comment]
You’re welcome! Feel free to open an issue if you have a question.
Thank you for your interest.
