### ISSUE TITLE
Real-time inference

### ISSUE THREAD

**Issue by kyungjin-lee** [mindslab-ai/voicefilter#3]
Hi, I'd like to use this voice filtering in real-time. Would it be possible to modify the inference code to run the model in real time for audio PCM data?

**Comment by seungwonpark** [comment]
Hi, @kyungjin-lee 
Yes, but it depends on what you mean by saying “real-time”.

On V100 GPU, I checked that the inferencing time is shorter than the length of the audio. However, if you meant streaming, you will have to change BiLSTM to unidirectional LSTM, and some other things should be changed. Model should be trained again if then of course.

**Comment by kyungjin-lee** [comment]
Yes, I did mean streaming. I'll give it a shot. Thanks!

**Comment by xiaozhuo12138** [comment]
If CNN input only one frame of data at a time, will the effect be very bad?

**Comment by johannesmols** [comment]
> Yes, I did mean streaming. I'll give it a shot. Thanks!

Did you have any luck with this? I am also interested in a real-time application of this.
