### ISSUE TITLE
fianl model

### ISSUE THREAD

**Issue by 0ifeng0** [mindslab-ai/voicefilter#7]
Is there any possible to provide the final  checkpoint ？The training takes too much time.

**Comment by seungwonpark** [comment]
Hi, @0ifeng0 
I'm afraid that I can't since the trained weights that I got is a private proprietary of my company.

Still, you can wait for other users to upload their final checkpoint.

Best, Seungwon Park

**Comment by 0ifeng0** [comment]
Thanks for reply.I will right here waiting for someone.

**Comment by seungwonpark** [comment]
Closing this issue as our conversation is done.
Feel free to add more comments here.

**Comment by AlexD123123** [comment]
> Thanks for reply.I will right here waiting for someone.



> Hi, @0ifeng0
> I'm afraid that I can't since the trained weights that I got is a private proprietary of my company.
> 
> Still, you can wait for other users to upload their final checkpoint.
> 
> Best, Seungwon Park

Hi Seungwon, 

Are there any news regarding a possible trained model for this paper?
Unfortunately I do not have access to reasonable training resources...

Thanks, 
Alex

**Comment by seungwonpark** [comment]
Hi, @AlexD123123 
I'm afraid that we still don't have a public one.

However, if you're interested, you may want to try our company's VoiceFilter web demo & API. You can try them without any charge for the first month. Just head to https://maum.ai and try it out. (You'll be prompted to enter your credit card info, though.)

**Comment by AlexD123123** [comment]
Thanks! Will check it out!

**Comment by batnik1** [comment]
> Thanks! Will check it out!

Hey, did you find that final checkpoint for the model? If yes, can you please direct me to where I can get it too!
