### ISSUE TITLE
how to create file embedder

### ISSUE THREAD

**Issue by giappham96** [mindslab-ai/voicefilter#8]
Hi, i'd like generate file embedder from my data. So how to create it. Many thanks.

**Comment by seungwonpark** [comment]
Hi, @giappham96 

If you want to train embedder from your own data, then perhaps you'll be interested in these open source projects:
- https://github.com/Janghyun1230/Speaker_Verification
- https://github.com/HarryVolek/PyTorch_Speaker_Verification

**Comment by giappham96** [comment]
Hi, @seonghoon-woo 
I seen you upload this file: https://drive.google.com/file/d/1YFmhmUok-W76JkrfA0fzQt3c-ZsfiwfL/view?usp=sharing
How do you create it from your data?

**Comment by seungwonpark** [comment]
We've used our own embedder training codebase. Unfortunately, we couldn't open-source that since it's proprietary software of our company.

**Comment by giappham96** [comment]
Thank you for contributing to the community.

**Comment by seungwonpark** [comment]
You're welcome. Thank you for your understanding.
